# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_auto_20171126_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='test_title',
        ),
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cinema',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
